### ISSUE TITLE
Quality Control: Extracted source tests

### ISSUE THREAD

**Issue by gijzelaerr** [transientskp/tkp#385]
Flag each individual source if they fail these quality checks - this test needs to occur in the source extraction recipe in TraP. If an extracted source fails this quality control check, it should not be used in the following source association, transient search and monitoring list steps. This means the monitoring list may do a force fit at this location later in the TraP. Do we want these tests running on monitoring list sources too or are there already similar tests for those forced fits?

This test will require a new column in the database for each individual source (Quality control) to be displayed on TKP-web on the individual extracted sources page. Using the PySE source extraction outputs flag a source if the error is X% of the value, where X is an integer user entry in the source extraction parset file (default 20%). The relevant values are from PySE output and already stored in the database:
1. ( (int_flux_err)/(int_flux) ) \* 100 = Y% > X% → “Large errors. Flux errors are Y% of total value.”
2. ( (smaj_err)/(smaj) ) \* 100 = Y% > X% → “Large errors. Ellipse major axis errors are Y% of total value. Ellipse major axis = smaj, Ellipse major axis error = smaj_err ”
3. ( (smin_err)/(smin) ) \* 100 = Y% > X% → “Large errors. Ellipse minor axis errors are Y% of total value. Ellipse minor axis = smin, Ellipse minor axis error = smin_err ”
4. This is looking for sources which are smaller than the restoring beam size: smin < bmin → flag with “Source smaller than beam. Beam minor axis = bmin, Source minor axis = smin”. bmin is in both the fits header (when using fits images) and in the LOFAR image format (AWImager images).

**There is more discussion in the original issue**:
https://support.astron.nl/lofar_issuetracker/issues/3797

**Comment by timstaley** [comment]
Speaking with Adam and Jess, poor fits are a major source of false transients, so we should try to implement this sooner rather than later - shouldn't be too hard. I'll bump priority accordingly.

**Comment by AntoniaR** [comment]
could you get them to post some examples? I'm surprised it makes that big a difference.

**Comment by timstaley** [comment]
@ajstewart (see above)

**Comment by ajstewart** [comment]
I've discussed two different issues recently with various people but the two issues regarding fits recently have been:

Firstly, I thought it would be good for TraP to be able to cut fits such as those seem in this image:

![susect_fits](https://cloud.githubusercontent.com/assets/3306161/6627890/48bbb80e-c8f9-11e4-9b3c-b254b8bc8446.png)

The large extractions I thought would be easy to cut and disregard. This is what happens when you use pyBDSM for example. They can populate the transient lists so it would be nice to eliminate them. I think when I referenced this issue to Tim, this was my main line of thought. Of course forcing the beam solves this issue but sometimes it's still useful to run without a forced beam, as with the next example.

The second issue was where the forced beam causes some flux to be 'missed' from sources when the morphology changes. For example this source below is deemed brighter in the images where it appears more elliptical then when it appears as a kind of double source - hence making it seem variable. But I don't think this issue is designed to try and combat this kind of behaviour, and actually it might be a bit difficult to? Not forcing the beam does reduce the variability of the source. This situation made me spawn a few other issues, mainly in banana, just to make it easier to diagnose these kind of situations. So I think my first issue was more along the lines of what I was thinking.

![bright](https://cloud.githubusercontent.com/assets/3306161/6628002/f0390f14-c8f9-11e4-9fc1-db9aae6ec171.png)

![dim](https://cloud.githubusercontent.com/assets/3306161/6627991/e4d32eac-c8f9-11e4-8e37-7ce952695de0.png)

![image](https://cloud.githubusercontent.com/assets/3306161/6628146/1047397e-c8fb-11e4-873e-fa3a1cd8b8b4.png)

**Comment by AntoniaR** [comment]
Very true about the fits without forced beam, I agree those are a big issue but I'm not sure if the fluxes are generally stable enough without the forced beam option anyway. But some point soon we need to prioritise what goes into the next TraP release and maybe this should go into that list.

You are also right about the morphology problem, I am also encountering something similar to this with some ATCA data which has very different resolutions. This issue wouldn't solve that sadly, but I'm also trying to think of good ways round it. Perhaps in a few weeks we should make the morphology problem a TraP meeting topic? We could present the different issues and then discuss short and long term solutions.

**Comment by timstaley** [comment]
NB this should be helped along when #409 is implemented.

**Comment by gijzelaerr** [comment]
isn't this something that should already happen in the source finder? Some of these bad fits are just huge and should probably never end up in the database right. I don't see added value of storing bad fits if we are not going to use them anyway. Maybe only for debugging procedures?

**Comment by AntoniaR** [comment]
I don't think this should be in the source finder because extended sources would have the same properties (a large, maybe elongated, ellipse) and this is the correct answer. So by automatically flagging these as bad in the sourcefinder could cause us to miss real sources and some people may want to know about the extended sources in the field - so potentially reduces the PySE capabilities. This is why I would prefer it as a configurable test in TraP.

**Comment by gijzelaerr** [comment]
ok then we implement it according to the original plan.

**Comment by AntoniaR** [comment]
This is an ongoing wish list item but not essential for R7. Moving to the long term milestone.

**Comment by HannoSpreeuw** [comment]
I guess this issue might turn out redundant with the [recently introduced bounds for Gaussian fits](https://github.com/transientskp/pyse/blob/3650d85acf57e06ad51256c062bd100b170ff493/sourcefinder/extract.py#L302).

In short, the peak spectral brightnesses, semi-major and semi-minor axes should be between 50% and 150% of the corresponding values from moments computations.
The fitted position should be within the island.
The position angle should be between $-\frac{\pi}{2}$ and $\pi$.

Wouldn't that cover 1, 2 and 3?

Not sure about 4: fitted source shape parameters smaller than the corresponding clean beam parameters....this can easily occur when fitting an unresolved source. Even moments analysis can yield this.
This means that one cannot deconvolve from the clean beam.
I guess in that case you might want to take account of this, either inside or outside PySE.

A wild idea....we could set the [lower bounds for the semi-major axis](https://github.com/transientskp/pyse/blob/3650d85acf57e06ad51256c062bd100b170ff493/sourcefinder/extract.py#L337) and the [semi-minor axis](https://github.com/transientskp/pyse/blob/3650d85acf57e06ad51256c062bd100b170ff493/sourcefinder/extract.py#L345) equal to the corresponding clean beam parameters. Not sure what you should set as an upper bound then....just as it is now, i.e. the corresponding value from "moments" * 1.5, if that is large enough?

Or you could take account of fitted shape parameters that are too small a posteriori, so outside PySE.

**Comment by AntoniaR** [comment]
It does sound like 1-3 are indeed fixed with the new options and I think 4 should be dropped now as I think there are probably cases where it would not perform well. So I think we should close this issue.
