### ISSUE TITLE
Measure RMS of image even if full quality control routine is not performed

### ISSUE THREAD

**Issue by ajstewart** [transientskp/tkp#392]
When running the TraP on data from telescopes other than LOFAR, e.g. the VLA, the RMS of images are not measured. Or at least are not displaying in banana on the 'images' page (all RMS columns are 0). 

This seems to be due to the fact that the quality control routine is not run because TraP doesn't have the information of how to calculate theoretical noise values for other telescopes - which I completely expect and understand. But I was surprised that the RMS of the image was not measured regardless of this as it is a value that can just be measured, no matter the telescope. I think it's useful to have these values for the images and perhaps should be changed so that it is always measured with or without the full quality control checks.

**Comment by AntoniaR** [comment]
This is a Banana display issue, TraP is correctly measuring the RMS for all images as it is used in the analysis of every new source to determine if they are transient or not. If you access the data directly from the database you can get the RMS values.

The issue is that with higher frequency images the RMS noise is significantly lower than LOFAR. e.g. in my ATCA images it's typically ~10^-4 Jy. Banana prints the RMS in Jy as a float rounded to 3 decimal places. Therefore, the RMS is rounded to 0.000 in the display.

This would be quickly solved by instead printing the RMS noise in scientific notation e.g. 2.5E-04

**Comment by ajstewart** [comment]
Ah ok - good to know. Maybe this issue should be moved or something then?

Maybe the toggle switch like the other pages? But thinking about it the scientific notation for this specific page might be better.

**Comment by AntoniaR** [comment]
Perhaps @timstaley knows how to transfer this issue to Banana?

**Comment by timstaley** [comment]
We just manually migrate it. If you drop in a hyperlink to another issue it will also note the reference in the cited issue, as you can see above.
