### ISSUE TITLE
parallellise sourefinder

### ISSUE THREAD

**Issue by gijzelaerr** [transientskp/tkp#416]
Sourcefinder gets slow on big images, parallellising could help.

Maybe this would imply a rewrite of some parts, since pyse has become a bit messy over time.

@hughbg has issued a parallellising PR a while ago, that PR got lost unfortunately. @hughbg can you have a look and try resurrect that? Then we have a look at your implementation and maybe polish that.

**Comment by jdswinbank** [comment]
It's also worth considering to what extent it's possible to parallelise the pipeline itself. That is: if you can run the sourcefinder on multiple images at the same time, it is likely both more efficient and less development effort than parallelising the operations over a single image.

Of course, there are some intrinsic limits to how far you can push this: we generally say you need to "process" all the images at timestep $t_n$ before moving on to $t_{n+1}$. However, that's only partially true. For example, off the top of my head I don't see any reason why you can't do blind source extraction on every image as soon as it's available, and then store the results until the rest of the pipeline is ready to process them.

I'm rusty on this part of the code, but I suspect the slowest part of running PySE is the background and RMS map calculation. Further, I suspect we do that at least twice per image during the run -- once on the initial blind extraction, and once later for picking up forced fits etc. It might be a significant win to arrange for them to be cached rather than recalculated (or I might just be misremembering; it is possible we already do this).

Of course, the above might help with pipeline throughput, but not if your aim is to run a standalone sourcefinder on a single image.

**Comment by gijzelaerr** [comment]
Thanks @jdswinbank for your thoughts. Yes, I've been thinking a lot in the past about this. Basically it boils down to rewrite the main flow as a graph with temporal input / output dependencies. 

This is a separate issue though, opened a new one for that https://github.com/transientskp/tkp/issues/418

**Comment by hughbg** [comment]
I see the pull request at https://github.com/transientskp/tkp/pull/294 and there is the issue https://redmine.astron.nl/lofar_issuetracker/issues/4732. If the pull request doesn't supply the code changes I can get them off my backup.

**Comment by gijzelaerr** [comment]
Hi @hughbg, Thanks for your message.

The PR is there, but the branch itself is gone, if you click on the files you will get a 404.

**Comment by timstaley** [comment]
This might just be because @hughbg 's fork of TKP is still private? @hughbg if you check your repositories, you may find you can just to go repo-settings and make it public again.

**Comment by hughbg** [comment]
Yes I got this message when trying to access the repository:
-------
This repository is currently disabled.

The repository this private fork was created from has been made public. To protect your code’s privacy, the fork is now a private repository under your account's ownership.

If you would like to make this repository public to match, please see the Make this repository public section on the repository’s settings page<https://github.com/hughbg/tkp/settings>.

If you would like to continue accessing this repository privately, pleaseupgrade your account<https://github.com/account/billing>.

--------


I've changed the settings so the repository is public.


     Hugh


________________________________

**Comment by gijzelaerr** [comment]
@hughbg can you make the repo public?

**Comment by timstaley** [comment]
A word to future TKP'ers - I'm pretty sure a good first step here is just to farm the 'island fitting' jobs out to a mulitprocessing pool, I think that will get us a good benefit for minimal effort. Some sourcefinder code clean-up would be nice first though. It's on the to-do list :)

**Comment by HannoSpreeuw** [comment]
> A word to future TKP'ers - I'm pretty sure a good first step here is just to farm the 'island fitting' jobs out to a mulitprocessing pool, I think that will get us a good benefit for minimal effort. Some sourcefinder code clean-up would be nice first though. It's on the to-do list :)

You could think of fixing this issue was the major part of my work for [PADRE](https://www.esciencecenter.nl/projects/the-petaflop-aartfaac-data-reduction-engine-padre/).

Indeed I implemented such parallellisations in PySE, e.g. parallellization of $\kappa\sigma$-clipping routines over the subimages that yield the node values for the background mode and background rms maps. I tried Ray first, then Dask.
Similarly a multiprocessing.Pool for parallellizing the source measurements.
And other speedups, for instance by implementing more efficient interpolation routines.

All relatively easy to implement, such parallellizations are low hanging fruit and give nice speedups......until you hit a wall at about 3s for processing a 2K *2K image. Then parallellizing any untouched part of PySE will not yield anything substantial.

For PADRE we wanted to get below 1s. It turned out that we could only get there by using compiled code; we used [sep](https://github.com/kbarbary/sep) for computing the background mode and background rms maps and Numba for compiling most of the subsequent calculations, by applying its amazing [guvectorize decorator](https://numba.readthedocs.io/en/stable/user/vectorize.html#the-guvectorize-decorator).

The end result is that [PySE's accelerated branch](https://github.com/transientskp/pyse/tree/3650d85acf57e06ad51256c062bd100b170ff493) can process a 4K * 4K image with 167,000 sources on a single core of a high-end CPU in 0.6s. Loading such an image from disk can take an additional 0.2-0.5s.

With hindsight, I should not have spent so much time on all these parallizations, they have all been removed in the accelerated branch.
