### ISSUE TITLE
sourcefinder returns wrong RA values for AARTFAAC data

### ISSUE THREAD

**Issue by gijzelaerr** [transientskp/tkp#450]
The sourcefinder returns the wrong RA value when given AARTFAAC images. When we apply a modulo 360 degrees to the RA the value becomes correct. 

Related: https://github.com/transientskp/banana/issues/89

**Comment by gijzelaerr** [comment]
This is the location where pixel values are converted to RA & DEC using WCS, where they are already wrong:

https://github.com/transientskp/tkp/blob/67dcb593bf96cf6fb1fab43a876c3c77f8186f80/tkp/sourcefinder/extract.py#L820

looks like WCS is not correctly initialized.

**Comment by gijzelaerr** [comment]
so this issue is related:

https://github.com/transientskp/tkp/issues/444

I'm setting CRVAL to pointing center. @ycendes will do a test run and see what happens. @hsuyeep and @Error323 are notified, but we can't do much more until they tell what the idea here is.

https://github.com/transientskp/tkp/commit/d97cdeb8ae198ea300a799af770fa5e1156c2ebb

**Comment by ycendes** [comment]
It's not a perfect fix.  I did a quick 2 image run (one where the number of sources abruptly jumps from one to the other) and in one the RAs are positive, and in the other negative.  After loading it up in DS9, the values given in RA are incorrect between what the source position is per TraP and what it is per DS9 (sexigesimal is, as always, correct).

Further, the sources found in this image where the RAs are still negative are clearly wrong: http://banana.transientskp.org/master/vlo_aashortertest/image/7158/ (and previously it could find the same 4 bright sources)

**Comment by hsuyeep** [comment]
OK, I think I found the problem. The imaging pipeline code has a bug where the ra/dec is set as the pointing direction:
https://github.com/transientskp/aartfaac-imaging-pipeline/blob/e5c483b55eb1fd57cc7ed5ccbfa5d1a06eaa72ff/src/pipeline/modules/output/CasaImageStorage.cpp#L83

The function setAngle  () expects radians, but we were supplying it with RA in hours. I've fixed this in [this](http://github.com/transientskp/aartfaac-imaging-pipeline/commit/6b32ac3cbdd41b0e11af8151779a377fe8fbb234) commit, but is still to be tested.

Here is a bit of code to replicate the problem:
```C++
#include <casacore/measures/Measures/MEpoch.h>
#include <casacore/measures/Measures/MCEpoch.h>
#include <casacore/measures/Measures.h>
#include <casacore/measures/Measures/MDirection.h>
#include <casacore/measures/Measures/MPosition.h>

int main ()
{
    casa::MPosition obs(casa::MVPosition(3826577.066110000, 461022.947639000, 5064892.786), casa::MPosition::ITRF);
    casa::MEpoch model (casa::Quantity (0., "d"));
    casa::MeasFrame frame(obs);
    casa::MEpoch::Ref outref(casa::MEpoch::LAST, frame);
    casa::MEpoch::Convert toLST(model, outref);

    /* Taking the date from some random images to generate the RA, then compare with ra in .image
       date --date="2013-11-21 00:04:57 UTC" +%s = 1384992297
        'crval': array([ 1.18659882,  0.91983159]),
        'pointingcenter': {'initial': False,
        'value': array([ 3.13493528,  0.92354311])},
    
       date --date="2013-11-20 13:37:00 UTC" +%s = 1384954620
       'crval': array([-1.55708834,  0.92020057])
       'pointingcenter': {'initial': False,
       'value': array([-2.84931288,  0.92354311])},
    */
    int unix_time[] = {1384992297, 1384954620} ;
    for (int i = 0; i<2; i++)
    {
        // Replicate the previous output.
        std::cout << "RA for unixtime "<< unix_time[i] << " is "<< toLST(unix_time[i]).getValue().getDayFraction()*12.0/M_PI << std::endl;
    }
    return 0;
}
```
Compile with: g++ testLST.cpp -I/usr/local/include/casacore -lcasa_measures -lcasa_casa
Output: 
RA for unixtime 1384992297 is 3.13494
RA for unixtime 1384954620 is 3.43387

Note that the pointing center remains the same if <2*M_PI, and is (2*M_PI-3.43387) = -2.84931530 otherwise.

The CRVAL has a different value because the code sets the reference longitude to 270, reflat to 90. It is still not clear to me why this is done,as I would expect it to be set to the pointing center, so I'll give it some more time.

**Comment by hsuyeep** [comment]
Fine, so I have now tested the fixed images with originally a negative RA,as well as a positive RA. There is another another change: the direction0 is now the pointing center, vide commit .
As you can see from the attachment, pyse is now quite happy with this arrangement. These changes are implemented by a tool in aartfaac-tools/fixpointing.py which will fix the older buggy images for you. (https://github.com/transientskp/aartfaac-tools/commit/9031a1e4e7594e29bc5a12ef0de45a7b061d57ee)

Call to pyse for the image shown: pyse.py new1.fits --regions --detection 4 --analysis 3
All the sources found by pyse have positive RA/Decs.
#### Image with originally a negative RA.:
f5 73257e 07_s1-63_t20-11-2013_13-37-00.image
![f5 73257e 07_s1-63_t20-11-2013_13-37-00_negra_ds9](https://cloud.githubusercontent.com/assets/1520321/9003725/bf3ae708-3770-11e5-8665-a97e1d49b174.png)

#### Image with originally a positive, but wrong RAs
f5 73257e 07_s1-63_t21-11-2013_00-04-57.image
![f5 73257e 07_s1-63_t21-11-2013_00-04-57_posra_ds9](https://cloud.githubusercontent.com/assets/1520321/9003729/d0610562-3770-11e5-9e0c-666b38c9b376.png)

**Comment by gijzelaerr** [comment]
Cool peeyush thx! I find it a bit weird though, I though Yvette checked the
coordinates of some of the objects and found they matched known sources,
but by the looks of the all positions where wrong?

Op vr 31 jul. 2015 11:38 schreef Peeyush Prasad <notifications@github.com>:

**Comment by hsuyeep** [comment]
So looks like the above conversion is still wrong, as the toLST() function seems to require a Julian Day as its parameter, instead of unixtime. I checked this by creating some times which vary by 1 min, getting the Julian day out of them, and then converting those times to RA, and then checking if the RAs vary by 1 min.
```C++
#include <casacore/measures/Measures/MEpoch.h>
#include <casacore/measures/Measures/MCEpoch.h>
#include <casacore/measures/Measures.h>
#include <casacore/measures/Measures/MDirection.h>
#include <casacore/measures/Measures/MPosition.h>

int main ()
{
    casa::MPosition obs(casa::MVPosition(3826577.066110000, 461022.947639000, 5064892.786), casa::MPosition::ITRF);
    casa::MEpoch model (casa::Quantity (0., "d"));
    casa::MeasFrame frame(obs);
    casa::MEpoch::Ref outref(casa::MEpoch::LAST, frame);
    casa::MEpoch::Convert toLST(model, outref);

    /* date --date="2013-11-21 00:04:57 UTC" +%s = 1384992297
        'crval': array([ 1.18659882,  0.91983159]),
        'pointingcenter': {'initial': False,
        'value': array([ 3.13493528,  0.92354311])},
    
       date --date="2013-11-20 13:37:00 UTC" +%s = 1384954620
       'crval': array([-1.55708834,  0.92020057])
       'pointingcenter': {'initial': False,
       'value': array([-2.84931288,  0.92354311])},
    */
    // int unix_time[] = {1384992297, 1384954620} ;
    int unix_time = 1384992297;
    casa::Time t1 (2013, 11,20,13,37);
    double t1jd = t1.julianDay();
    std::cout << "T1 Julian day: "<< t1jd;
    for (int i = 0; i<10; i++)
    {
        // Replicate the previous output.
        double newtime = t1jd + i*60.0/86400.0;
        printf ("RA for julianDay %.3f is %10.5f.\n", newtime, toLST(newtime).getValue().getDayFraction()*24);
    }
    return 0;
}
```

Output: 
T1 Julian day: 2.45662e+06RA for julianDay 2456617.067 is    5.77996.
RA for julianDay 2456617.068 is    5.79668.
RA for julianDay 2456617.069 is    5.81339.
RA for julianDay 2456617.069 is    5.83010.
RA for julianDay 2456617.070 is    5.84681.
RA for julianDay 2456617.071 is    5.86352.
RA for julianDay 2456617.072 is    5.88024.
RA for julianDay 2456617.072 is    5.89695.
RA for julianDay 2456617.073 is    5.91366.
RA for julianDay 2456617.074 is    5.93037.

The consecutive RA outputs differ by 1 min, as expected:
(5.93037 - 5.91366)*60
1.00260

**Comment by gijzelaerr** [comment]
I think this is actually working correctly now. @ycendes can you verify so we can close this issue.

**Comment by ycendes** [comment]
After checking (on the test data set that Peeyush ran yesterday), the good news is it appears that the RA values in the images are now all correct when it comes to comparing to sexagesimal and are consistent.  Yay!  The bad news is when you check the brightest sources in the AARTFAAC images they do *not* overlap with sources in the catalog in all cases. (You can now do this in Banana quite easily by checking the running catalog- thanks Gijs! Who also confirmed it lines up fine for non-AA images.)

So it appears there is still some issue in the AARTFAAC images when it comes to pointing in the right direction, but that's not a TraP thing.

**Comment by gijzelaerr** [comment]
I added the nvss catalog and made it the default.

I think we can conclude that this is not a TraP issue but something with the aartfaac imaging pipeline, so lets move the discussion there and close this issue. 

https://github.com/transientskp/aartfaac-imaging-pipeline/issues/18
