### ISSUE TITLE
Image size limit

### ISSUE THREAD

**Issue by ajstewart** [transientskp/tkp#553]
Does anyone know what the limit is for the size of the images the TraP can take? Also what is the limiting factor? I have some large images (9450 x 9450) which are failing, and something along these lines rings a bell...

**Comment by mkuiack** [comment]
How is it failing? Can you post the output of the error log? 

To my knowledge there isn't any hard limit on the size hardcoded in but it might be related to memory requirements.

**Comment by tremou** [comment]
Here it is (I have the same issue)
[trap.log](https://github.com/transientskp/tkp/files/1710984/trap.log)

**Comment by gijzelaerr** [comment]
Since trap4, the images are stored in the database. You reached the limit of the storage size of your database. You can work around this by disabling the 'image store' or 'image cache', forgot the name. The disadvantage is that the images don't show anymore in banana. The advantage is that trap will run much faster also.

**Comment by tremou** [comment]
That works, yes. Thanks!

**Comment by ajstewart** [comment]
Ah ok thanks for that!

And thanks @tremou for providing the log.
